I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 43, in script
    $ raise Exception("DO NOT CONTINUE")
  File "game/script.rpy", line 43, in <module>
    $ raise Exception("DO NOT CONTINUE")
Exception: DO NOT CONTINUE

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 43, in script
    $ raise Exception("DO NOT CONTINUE")
  File "C:\Users\betha\Documents\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\betha\Documents\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 43, in <module>
    $ raise Exception("DO NOT CONTINUE")
Exception: DO NOT CONTINUE

Windows-8-6.2.9200
Ren'Py 7.3.5.606
DDLC2: The Corruption 1.0
Fri Mar 05 16:59:59 2021
